// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGUQK6HYZSZukd0YSBriPdkbmkSYhCPVQ',
    appId: '1:897064633184:web:dbc1bbe10ff49d3b3f5405',
    messagingSenderId: '897064633184',
    projectId: 'sondage-c0c79',
    authDomain: 'sondage-c0c79.firebaseapp.com',
    storageBucket: 'sondage-c0c79.firebasestorage.app',
    measurementId: 'G-B6N4XRKTHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDul-p4IkqyDGGXkmc7AGf__DJZGmipc6s',
    appId: '1:897064633184:android:c0646d26bbc38cbd3f5405',
    messagingSenderId: '897064633184',
    projectId: 'sondage-c0c79',
    storageBucket: 'sondage-c0c79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2vkQ-EdCoIba5XjLgAe6iQ9ZhgkquYpA',
    appId: '1:897064633184:ios:32d8a0fb6906437c3f5405',
    messagingSenderId: '897064633184',
    projectId: 'sondage-c0c79',
    storageBucket: 'sondage-c0c79.firebasestorage.app',
    iosBundleId: 'com.example.sondage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2vkQ-EdCoIba5XjLgAe6iQ9ZhgkquYpA',
    appId: '1:897064633184:ios:32d8a0fb6906437c3f5405',
    messagingSenderId: '897064633184',
    projectId: 'sondage-c0c79',
    storageBucket: 'sondage-c0c79.firebasestorage.app',
    iosBundleId: 'com.example.sondage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGUQK6HYZSZukd0YSBriPdkbmkSYhCPVQ',
    appId: '1:897064633184:web:331be524546aa3a33f5405',
    messagingSenderId: '897064633184',
    projectId: 'sondage-c0c79',
    authDomain: 'sondage-c0c79.firebaseapp.com',
    storageBucket: 'sondage-c0c79.firebasestorage.app',
    measurementId: 'G-JZ13XYS76S',
  );
}
